version: '3'
services:
    media_importer:
      build: .
      container_name: lucos_media_import
      volumes:
        - "media:/medlib/ceol srl"
      environment:
        - MEDIA_API
        - MEDIA_DIRECTORY=/medlib/ceol srl
        - MEDIA_PREFIX
        - KEY_LUCOS_MEDIA_METADATA_API
      image: lucas42/lucos_media_import
      restart: always

volumes:
  media:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=aurora.local,ro,nolock,hard,intr,retry=3"
      device: ":/medlib/ceol srl"