version: '3'
services:
    media_importer:
      build: .
      container_name: lucos_media_import
      volumes:
        - "media:/medlib/ceol srl"
      environment:
        - MEDIA_API
        - MEDIA_DIRECTORY
        - MEDIA_PREFIX
      image: lucas42/lucos_media_import

volumes:
  media:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=aurora,ro,nolock,hard,intr,retry=3"
      device: ":/medlib/ceol srl"